### ISSUE TITLE
How to compile it?

### ISSUE THREAD

**Issue by USBEprom** [bradgrantham/sd_card_spi_tests#1]
Sorry to bother.
How to compile the whole thing on Windows and Linux?
I am pretty babo, sorry.
Thanks in advance.

**Comment by bradgrantham** [comment]
Install or compile libbuspirate, then "make" on Linux or Mac.  Windows is not supported, sorry!

Note added to README.md in d31f01ad1c0ef1ade278c169d900937d8d1b1761

**Comment by USBEprom** [comment]
Thank you Sir, you are very kind.
I am trying it on Ubuntu right now.
